services:
  qrcode-generator:
    image: nginx:1.27.5-alpine-slim
    container_name: qrcode-generator
    ports:
      - "8886:80"
    volumes:
      - ./:/usr/share/nginx/html
    environment:
      - NGINX_HOST=0.0.0.0
    restart: unless-stopped